# Setup
title: Project or Site name
tagline: Blessing's blog post
baseurl:
url:

paginate: 1
locale: 'en'
# About/contact
author:
  name: Author name
  # url: http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
